version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: ../docker/server.Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URL=${MONGODB_URL}
      - DATABASE_URL=${DATABASE_URL}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT}
    restart: unless-stopped